---

- name: ansible podman play
  hosts: adm
  remote_user: student
  become: yes
  become_method: sudo 
  # var_files:
  #   - groups_vars/all/main.yml
  roles:
    - { role: ansible-podman-role } 
